namespace Simem.AppCom.Base.Utils
{
    public enum KeyVaultTypes
    {
        AzureStorage,
        StorageContainer,
        PQEEndpoint,
        user_pqr,
        pass_pqr,
        SimemConnection,
        ClBuzonPQR,
        BuzonPQR,
        urlCrmLogin,
        urlCrmData,
        crmStatus,
        crmModuleName,
        crmWindow,
        crmWorkTeam,
        crmPriority,
        secretKeyJWT,
        ContactanosFalla,
        DocumentalUrl,
        DocumentalUser,
        DocumentalPass,
        DocumentalClaseDocumental,
        DocumentalDebeResponder,
        DocumentalDependencia,
        DocumentalMedioRecibido,
        UrlContactanos,
        FilesUrl,
        FrontUrl
    }
}
